version: 2
jobs:
  test:
    docker:
      - image: node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  build_and_deploy:
    machine: true
    steps:
      - checkout
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t mattflow/auth-service:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push mattflow/auth-service:$TAG

workflows:
  version: 2
  test_build_and_deploy:
    jobs:
      - test
      - build_and_deploy:
        requires:
          - test
