workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      - test
      - build-and-deploy:
          context: docker-deploy
          requires:
            - test

version: 2
jobs:
  test:
    docker:
      - image: node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  build-and-deploy:
    machine: true
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t mattflow/auth-service:$TAG .
      - run: docker push mattflow/auth-service:$TAG
