version: 2
jobs:
  test_build_deploy:
    docker:
      - image: node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - setup_remote_docker:
          version: 20.10.7
      - run: docker build -t mattflow/auth-service .

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test_build_deploy
