version: 2
jobs:
  test:
    docker:
      - image: node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  build:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: docker build -t mattflow/auth-service .
      - setup_remote_docker:
        version: 20.10.7

workflows:
  version: 2
  test_build:
    jobs:
      - test
      - build
